name: RISE Code Coverage Report
description: Comments a pull request with the code coverage
author: Romeo Van Snick, Armin Ghajar Jazi
branding:
  icon: percent
  color: green
inputs:
  github-token:
    description: Github token
    required: true
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  subproject:
    description: projects folder in repo, where the coverage report is generated
    required: false
runs:
  using: node12
  main: dist/main.js
